files:
  - source: /translations/source.csv
    translation: /translations/%two_letters_code%/%original_file_name%
    first_line_contains_header: 1
    scheme: 'identifier,source_or_translation,context'
